update template
tc39/template-for-proposals pull request #31
Opened 2022-04-07 08:47 UTC by Jack-Works

2022-04-07 13:16 UTC, ljharb requested changes

2022-04-07 13:16 UTC, ljharb commented on package.json
> +    "@tc39/ecma262-biblio": "latest",
this should not be using `latest`, it should be using a semver range. v2 of this package has a breaking change compared to v1, for example.

2022-04-07 13:16 UTC, ljharb commented on spec.emu
> +stage: 0
```suggestion
stage: -1
```
it's not stage 0 until it's presented or on an agenda; i'd prefer that to be an explicit action.

2022-04-08 05:39 UTC, Jack-Works commented on package.json
> +    "@tc39/ecma262-biblio": "latest",
```suggestion
    "@tc39/ecma262-biblio": "^2",
```

2022-04-08 16:44 UTC, ljharb approved these changes
Thanks!

2022-04-08 16:45 UTC, merged